// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(PP
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWyfbP2xcsSOSwl0lA3XQZ-uaqx8H8nqQ',
    appId: '1:560347402739:web:5462995305727be63d0286',
    messagingSenderId: '560347402739',
    projectId: 'chat-app-3a054',
    authDomain: 'chat-app-3a054.firebaseapp.com',
    storageBucket: 'chat-app-3a054.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN3aHBXUY52BQGXnfwNshOfzYdXea3YAQ',
    appId: '1:560347402739:android:6f1e9b77401cd6733d0286',
    messagingSenderId: '560347402739',
    projectId: 'chat-app-3a054',
    storageBucket: 'chat-app-3a054.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABmgMVzd2u_9wKGc82kmAik8G4t9Dgtug',
    appId: '1:560347402739:ios:e69704a7709f83a63d0286',
    messagingSenderId: '560347402739',
    projectId: 'chat-app-3a054',
    storageBucket: 'chat-app-3a054.appspot.com',
    iosBundleId: 'com.example.catApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABmgMVzd2u_9wKGc82kmAik8G4t9Dgtug',
    appId: '1:560347402739:ios:28c5d254841ecfc13d0286',
    messagingSenderId: '560347402739',
    projectId: 'chat-app-3a054',
    storageBucket: 'chat-app-3a054.appspot.com',
    iosBundleId: 'com.example.catApp1.RunnerTests',
  );
}
